server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    display-name: Kanban board
  flyway:
    schemas: public
  datasource:
    hikari:
      connectionTimeout: 20000
      idleTimeout: 20000
      maxLifetime: 60000
      maximum-pool-size: 5
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://host.docker.internal:49153/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASS:postgrespw}
  jpa:
    hibernate:
      show-sql: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
